<a href="https://colab.research.google.com/github/Ngoc99/lab8/blob/master/3_Lab_MLP_for_Iris.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Multilayer Perceptron for Iris dataset

- Nguyễn Hữu Vũ 
- Nhóm nghiên cứu về AI đại học Bách Khoa Tp. Hồ Chí Minh

In [16]:

from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import numpy as np

In [17]:
# Load the iris dataset
iris = datasets.load_iris()

# Create our X and y data
X = iris.data
y = iris.target

## 1) Khám phá dữ liệu

In [18]:
X.shape

(150, 4)

In [19]:
y.shape

(150,)

In [20]:
X[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [21]:
# View the first five observations of our y data
y[:5]

array([0, 0, 0, 0, 0])

In [22]:
# Split the data into 70% training data and 30% test data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [23]:
X_train[:5]

array([[6.1, 2.9, 4.7, 1.4],
       [5.7, 2.8, 4.5, 1.3],
       [4.9, 3.6, 1.4, 0.1],
       [4.6, 3.2, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4]])

## 2) Chuẩn bị dữ liệu

In [24]:
# Train the scaler, which standarizes all the features to have mean=0 and unit variance
sc = StandardScaler()
sc.fit(X_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [25]:
# Apply the scaler to the X training data
X_train_std = sc.transform(X_train)

# Apply the SAME scaler to the X test data
X_test_std = sc.transform(X_test)

In [26]:
X_train_std[:5]

array([[ 0.38211563, -0.39023174,  0.61998358,  0.35048192],
       [-0.10569156, -0.60475704,  0.50597609,  0.21810566],
       [-1.08130592,  1.11144537, -1.26113999, -1.37040954],
       [-1.4471613 ,  0.25334417, -1.26113999, -1.23803327],
       [-0.47154694,  1.75502128, -1.09012875, -0.97328074]])

In [27]:
X_test_std[:5]

array([[-0.83740233,  1.54049597, -0.97612126, -0.97328074],
       [-0.95935412, -1.67738355, -0.17806884, -0.17902314],
       [ 1.1138264 ,  0.03881886,  1.13301728,  1.67424459],
       [-1.08130592, -1.46285825, -0.17806884, -0.17902314],
       [ 2.33334435, -0.17570644,  1.41803601,  1.54186832]])

## 3) Xây dựng model Perceptron

In [28]:
# Create a perceptron object with the parameters: 40 iterations (epochs) over the data, and a learning rate of 0.1
ppn = Perceptron(max_iter=40, eta0=0.1, random_state=0)


In [29]:

# Train the perceptron
ppn.fit(X_train_std, y_train)

Perceptron(alpha=0.0001, class_weight=None, early_stopping=False, eta0=0.1,
           fit_intercept=True, max_iter=40, n_iter_no_change=5, n_jobs=None,
           penalty=None, random_state=0, shuffle=True, tol=0.001,
           validation_fraction=0.1, verbose=0, warm_start=False)

In [30]:
#The actual number of iterations to reach the stopping criterion. For multiclass fits, it is the maximum over every binary fit.
ppn.n_iter_ 

11

##### Prediction

In [31]:
# Apply the trained perceptron on the X data to make predicts for the y test data
y_pred = ppn.predict(X_test_std)
y_pred

array([0, 1, 2, 1, 2, 1, 0, 2, 1, 2, 2, 1, 2, 2, 2, 0, 1, 0, 1, 1, 2, 2,
       0, 0, 1, 2, 0, 0, 1, 1, 0, 2, 1, 1, 2, 0, 2, 2, 2, 0, 1, 0, 1, 2,
       1])

In [32]:
# View the accuracy of the model, which is: 1 - (observations predicted wrong / total observations)
print('Accuracy: %.2f' % accuracy_score(y_test, y_pred))

Accuracy: 0.91


## 4) Xây dựng model MLPClassifier

In [33]:
from sklearn.neural_network import MLPClassifier

clf = MLPClassifier(hidden_layer_sizes=(8,5 ), activation='tanh', solver='sgd', 
                    alpha=0.0000001, batch_size=4, learning_rate='constant', learning_rate_init=0.005, 
                    power_t=0.5, max_iter=500, shuffle=True, random_state=11, tol=0.00001, 
                    verbose=True, warm_start=False, momentum=0.8, nesterovs_momentum=True, 
                    early_stopping=False, validation_fraction=0.2, 
                    beta_1=0.9, beta_2=0.999, epsilon=1e-08)


In [34]:

# Train the perceptron
clf.fit(X_train_std, y_train)

Iteration 1, loss = 1.05785003
Iteration 2, loss = 0.82548689
Iteration 3, loss = 0.68967166
Iteration 4, loss = 0.60454779
Iteration 5, loss = 0.54597855
Iteration 6, loss = 0.50556334
Iteration 7, loss = 0.47371852
Iteration 8, loss = 0.44872418
Iteration 9, loss = 0.42856772
Iteration 10, loss = 0.40660593
Iteration 11, loss = 0.38691857
Iteration 12, loss = 0.36583292
Iteration 13, loss = 0.34498322
Iteration 14, loss = 0.32652911
Iteration 15, loss = 0.30637807
Iteration 16, loss = 0.28729549
Iteration 17, loss = 0.27026334
Iteration 18, loss = 0.25265251
Iteration 19, loss = 0.23807192
Iteration 20, loss = 0.22183609
Iteration 21, loss = 0.20832608
Iteration 22, loss = 0.19650441
Iteration 23, loss = 0.18359818
Iteration 24, loss = 0.17092628
Iteration 25, loss = 0.16138977
Iteration 26, loss = 0.15197293
Iteration 27, loss = 0.14409145
Iteration 28, loss = 0.13989108
Iteration 29, loss = 0.12948048
Iteration 30, loss = 0.12409988
Iteration 31, loss = 0.11975852
Iteration 32, los

MLPClassifier(activation='tanh', alpha=1e-07, batch_size=4, beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(8, 5), learning_rate='constant',
              learning_rate_init=0.005, max_fun=15000, max_iter=500,
              momentum=0.8, n_iter_no_change=10, nesterovs_momentum=True,
              power_t=0.5, random_state=11, shuffle=True, solver='sgd',
              tol=1e-05, validation_fraction=0.2, verbose=True,
              warm_start=False)

In [35]:
clf.classes_ 

array([0, 1, 2])

In [36]:
clf.n_layers_ 

4

In [37]:
clf.n_outputs_ 

3

In [38]:
clf.out_activation_ 

'softmax'

- 1 input, 2 hidden, 1 ouput: => 4
- Thông thường trong Neural Networks, sẽ ko tính input layers, nên  trong Neural Networks, trường hợp này số Layers sẽ là 3

In [39]:
# Evaluate acuracy on test data
score = clf.score(X_test_std,y_test)
print("Acuracy (on test set) = ", score)

Acuracy (on test set) =  0.9777777777777777


- Ta thấy chỉ cần tăng #Layers, #Units độ chính xác sẽ tăng cao